branches:
  only:
  - blog

language: node_js

node_js:
- '0.10'

before_install:
- openssl aes-256-cbc -K $encrypted_bf7ae6d2ed82_key -iv $encrypted_bf7ae6d2ed82_iv -in .travis/ssh_key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'lephones'
- git config --global user.email 'lephones@lephones.net'

install:
- npm install hexo@2.8.3 -g
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save


script:
- hexo clean
- hexo g
- hexo d
