branches:
  only:
  - blog

language: node_js

node_js:
- '0.10'

before_install:
- git config --global user.name 'lephones'
- git config --global user.email 'lephones@lephones.net'

install:
- npm install hexo-cli -g
- npm install hexo --save
- npm install hexo-deployer-git --save
- npm install hexo-generator-archive --save
- npm install hexo-generator-category --save
- npm install hexo-generator-feed --save
- npm install hexo-generator-index --save
- npm install hexo-generator-sitemap --save
- npm install hexo-generator-tag --save
- npm install hexo-renderer-ejs --save
- npm install hexo-renderer-marked --save
- npm install hexo-renderer-stylus --save

script:
- hexo clean
- hexo g
- hexo d
