menu:
  首页: /
  关于我: /about
  归档: /archives
  RSS: /atom.xml
  网站地图: /sitemap.xml
widgets:
- search
- about_me
- category
- tag
- recent_posts
- recent_comment
- links

excerpt_link: Read More

twitter:


addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: 
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light